### ISSUE TITLE
Write user stories and document proposed updates from hiveplot research readout

### ISSUE THREAD

**Issue by cmajel** [ncats/nih-ncats-translator#83]
## User Story

We should take the items documented in our [research findings readout](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_113) from the hive plot usability test and write them as issues for further testing / iteration.

## Definition of Done

Issues are created for the following insights [identified in #41](https://github.com/ncats/nih-ncats-translator/issues/41#issuecomment-524991186) 

Per our grooming session today, here are the issues from our readout that we should document in git:

### Specific to the application

- [x] #79 Test an alternative label for `data` to identify knowledge assertions 
- [x] https://github.com/ncats/nih-ncats-translator/issues/107 Changes to the map were often unnoticed. Providing animation or more visible filter flags may help with this ([Slide 25 and 27](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_113))
- [x] https://github.com/ncats/nih-ncats-translator/issues/116 Overflow points were not obvious and interpreted as something else ([slide 25](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_113))
- [x] https://github.com/ncats/nih-ncats-translator/issues/117 It can be hard to select connections just by click. A zoom function could help with this. ([Slide 25 and 27](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_113))

### Future features
- [x] https://github.com/ncats/nih-ncats-translator/issues/118 How can we help show history and avoid lost work? ([Slide 26 and 27](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_120))
- [x] https://github.com/ncats/nih-ncats-translator/issues/119 How could we help users access / work with Translator data in multiple ways? ([Slide 26](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_120))
- [x] https://github.com/ncats/nih-ncats-translator/issues/120 How do we help people share what they find in Translator ([Slide 26](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_120))

### Larger questions

- [x] https://github.com/ncats/nih-ncats-translator/issues/105 Provide ways to understand translator on its own terms outside of other tools. ([Slide 14](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5fde3712e1_0_295))
- [x] https://github.com/ncats/nih-ncats-translator/issues/79 How many of the data sources consumed by Translator are publication databases? What are the other data source types? ([slide 23](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_83))
- [x] https://github.com/ncats/nih-ncats-translator/issues/28 Should connections based on publication databases be returned as publications, rather than data? ([slide 18](https://docs.google.com/presentation/d/1YvZ2ZNDxGND2-8WzEV7d2-eWR3w-wT93stdvAwHXkCQ/edit#slide=id.g5f422bc862_2_39))
- [x] #29 How can we “show our work” for data / knowledge assertion connections so users can see why they got this result?

**Comment by cmajel** [comment]
This is all set 🎉 🎉 

Closing - feel free to reopen if items are missing.
